name: graphcast
channels:
  - conda-forge
dependencies:
  - python=3.11
  - dm-tree
  - netcdf4
  - xarray
  - cartopy
  - boto3
  - pygrib
  - eccodes
  - iris
  - iris-grib
  - jupyterlab
  - pip
  - pip:
    - git+https://github.com/Benedict-Hyland/graphcast.git@main#egg=graphcast
    - flax==0.8.3
    - jax==0.4.31
